from speech_components.speech_recognizer.whisper_speech_recognizer import FasterWhisperSpeechRecognizer, QuantizeType
from speech_components.phoneme_to_viseme.phonemizer_mapper import PhonemizerMapper